baseURL = 'https://madeyourday.life/'
title = 'MadeYourDay.Life'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

[permalinks]
  posts = '/:section/:title/'
  guides = '/:section/:title/'
  galleries = '/:section/:title/'

[params]
  description = 'Travel adventures and guides'
  author = 'MadeYourDay.Life'

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    title = 'MadeYourDay.Life'
    [languages.en.params]
      description = 'Travel adventures and guides'

  [languages.tw]
    languageCode = 'zh-TW'
    languageName = '繁體中文'
    weight = 2
    title = 'MadeYourDay.Life'
    contentDir = 'content'
    [languages.tw.params]
      description = '旅遊冒險與攻略'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[imaging]
  quality = 85
  resampleFilter = 'CatmullRom'
  anchor = 'Center'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
